project_name: chart-releaser
builds:
  - main: cr/main.go
    binary: cr
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
    goos:
      - linux
      - darwin
      - windows
    ldflags:
      - >-
        -X github.com/helm/chart-releaser/cr/cmd.Version={{ .Tag }}
        -X github.com/helm/chart-releaser/cr/cmd.GitCommit={{ .Commit }}
        -X github.com/helm/chart-releaser/cr/cmd.BuildDate={{ .Date }}
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
