name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Tag
        run: |
          tag='${{ github.event.inputs.version }}'
          git tag --annotate --message "Tag for release $tag" "$tag"
          git push "https://x-access-token:${{ secrets.CI_TOKEN }}/$GITHUB_REPOSITORY" "refs/tags/$tag"

      - name: Test
        run: mage -v test

      - name: Release
        run: mage -v release
        env:
          GITHUB_TOKEN: "${{ secrets.CI_TOKEN }}"
